services:
  postgres:
    image: postgres:16-alpine
    container_name: ffh-postgres
    environment:
      POSTGRES_USER: ffh
      POSTGRES_PASSWORD: ffh_secret
      POSTGRES_DB: featureflaghub
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ffh -d featureflaghub"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
